DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS cloudinary CASCADE;



CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email VARCHAR NOT NULL UNIQUE,
  password_hash VARCHAR NOT NULL

);

CREATE TABLE favorites (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username BIGINT REFERENCES users(id),
  makeup_name TEXT NOT NULL,
  image_link TEXT NOT NULL,
  brand TEXT NOT NULL,
  color TEXT NOT NULL,
  hex TEXT NOT NULL,
  product_link TEXT NOT NULL
);

CREATE TABLE cloudinary (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username BIGINT REFERENCES users(id),
  imageurl TEXT NOT NULL,
  date TEXT NOT NULL
)
